
#include "main.h"
#include "eth/eth.h"
#include "eth/mdio.h"
#include "uart/uart.h"

#pragma message "MDC_GPIO: GPIO" STR(MDC_GPIO) " PIN" STR(MDC_PIN)
#pragma message "MDIO_GPIO: GPIO" STR(MDIO_GPIO) " PIN" STR(MDIO_PIN)
#pragma message "ETH_RESET_GPIO: GPIO" STR(ETH_RESET_GPIO) " PIN" STR(ETH_RESET_PIN)
#pragma message "ETH_REFCLK_GPIO: GPIO" STR(ETH_REFCLK_GPIO) " PIN" STR(ETH_REFCLK_PIN)
#pragma message "ETH_CRSDV_GPIO: GPIO" STR(ETH_CRSDV_GPIO) " PIN" STR(ETH_CRSDV_PIN)
#pragma message "ETH_RXD0_GPIO: GPIO" STR(ETH_RXD0_GPIO) " PIN" STR(ETH_RXD0_PIN)
#pragma message "ETH_RXD1_GPIO: GPIO" STR(ETH_RXD1_GPIO) " PIN" STR(ETH_RXD1_PIN)
#pragma message "ETH_TXEN_GPIO: GPIO" STR(ETH_TXEN_GPIO) " PIN" STR(ETH_TXEN_PIN)
#pragma message "ETH_TXD0_GPIO: GPIO" STR(ETH_TXD0_GPIO) " PIN" STR(ETH_TXD0_PIN)
#pragma message "ETH_TXD1_GPIO: GPIO" STR(ETH_TXD1_GPIO) " PIN" STR(ETH_TXD1_PIN)

void HAL_ETH_MspInit(ETH_HandleTypeDef *heth)
{
    GPIO_InitTypeDef gpio_init;

    __GPIOA_CLK_ENABLE();
    __GPIOC_CLK_ENABLE();
    __GPIOG_CLK_ENABLE();

    GPIO_INIT(MDC_GPIO, MDC_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);
    GPIO_INIT(MDIO_GPIO, MDIO_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);

    GPIO_INIT(ETH_RESET_GPIO, ETH_RESET_PIN, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FAST, 0);
    HAL_GPIO_WritePin(GPIO(ETH_RESET_GPIO), PIN(ETH_RESET_PIN), GPIO_PIN_SET);

    GPIO_INIT(ETH_REFCLK_GPIO, ETH_REFCLK_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);

    GPIO_INIT(ETH_CRSDV_GPIO, ETH_CRSDV_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);
    GPIO_INIT(ETH_RXD0_GPIO, ETH_RXD0_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);
    GPIO_INIT(ETH_RXD1_GPIO, ETH_RXD1_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);

    GPIO_INIT(ETH_TXEN_GPIO, ETH_TXEN_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);
    GPIO_INIT(ETH_TXD0_GPIO, ETH_TXD0_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);
    GPIO_INIT(ETH_TXD1_GPIO, ETH_TXD1_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF11_ETH);

    __ETH_CLK_ENABLE();
    uart_send_str3("HAL_ETH_MspInit", 1);
}

