
include ../util/util1.mk
C_SRCS += main.c
include $(ROOT_DIR)/gpio/gpio.mk
include $(ROOT_DIR)/pcl/pcl.mk
include $(ROOT_DIR)/tim/tim.mk
#include $(ROOT_DIR)/usb/usb.mk
#include $(ROOT_DIR)/uart/uart.mk
include eth.mk
include $(UTIL_DIR)/util2.mk

