
include ../util/util1.mk
C_SRCS += main.c
include $(ROOT_DIR)/flash/flash.mk
include $(ROOT_DIR)/gpio/gpio.mk
#include $(ROOT_DIR)/i2c/i2c.mk
include $(ROOT_DIR)/pcl/pcl.mk
include $(ROOT_DIR)/rng/rng.mk
#include $(ROOT_DIR)/tim/tim.mk
include $(ROOT_DIR)/uart/uart.mk
#include $(ROOT_DIR)/usb/usb.mk
#include $(ROOT_DIR)/vfd/vfd.mk
include eth.mk
include $(UTIL_DIR)/util2.mk

