
#include <main.h>

void HAL_SD_MspInit(SD_HandleTypeDef *hsd)
{
    GPIO_InitTypeDef gpio_init;
    GPIO_INIT(SDIO_CMD_GPIO, SDIO_CMD_PIN, GPIO_MODE_AF_PP, GPIO_NOPULL, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_CK_GPIO, SDIO_CK_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D0_GPIO, SDIO_D0_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D1_GPIO, SDIO_D1_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D2_GPIO, SDIO_D2_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D3_GPIO, SDIO_D3_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D4_GPIO, SDIO_D4_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D5_GPIO, SDIO_D5_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D6_GPIO, SDIO_D6_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    GPIO_INIT(SDIO_D7_GPIO, SDIO_D7_PIN, GPIO_MODE_AF_PP, GPIO_PULLUP, GPIO_SPEED_FAST, GPIO_AF12_SDIO);
    __HAL_RCC_SDIO_CLK_ENABLE();
    __HAL_RCC_DMA2_CLK_ENABLE();
}

void HAL_SD_MspDeInit(SD_HandleTypeDef *hsd)
{
}

