
include ../scripts/util1.mk
C_SRCS += main.c
include cptr.mk
include $(ROOT_DIR)/gpio/gpio.mk
include $(ROOT_DIR)/uart/uart.mk
include $(ROOT_DIR)/tim/tim.mk
include $(ROOT_DIR)/usb/usb.mk
include $(ROOT_DIR)/pcl/pcl.mk
include $(ROOT_DIR)/eth/eth.mk
include $(ROOT_DIR)/scripts/util2.mk

