
include ../util/util1.mk
C_SRCS += main.c
include display.mk
include $(ROOT_DIR)/gpio/gpio.mk
include $(ROOT_DIR)/uart/uart.mk
include $(ROOT_DIR)/pcl/pcl.mk
include $(ROOT_DIR)/i2c/i2c.mk
include $(ROOT_DIR)/tim/tim.mk
include $(UTIL_DIR)/util2.mk

